[options]
admin_passwd = $pbkdf2-sha512$600000$WivF.D.HsJbyvhdi7L231g$eEw4SR01hWXCJaMcXgTDyT4qsPwcrzGUjxklfMiGah2s8fmeeME.fpYyfMNjKJZp4DCGGE.d8gsoEo1nB6GkrA
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo

